list1 = ["apple,", "guava", "mango", "bananna", "kiwi"]
print("elements of lists are:", list1 )
print("the length of list is:", len(list1))
print('accessing the first element from the list: ', list1[0])
print('slicing the elements:', list1[1:4])
list1.append("pomogranate")
print('appending the elements of list: ', list1)
list1.pop(1)
print("popping the element of lists:", list1)
list1.remove("mango")
print('removing the element of list:', list1)
list1.sort()
print("sorting the elements:", list1)
list1.reverse()
print("reversing the list:", list1)
list1.clear()
print("deleting all elements of list:", list1)